### ISSUE TITLE
What is channel?

### ISSUE THREAD

**Issue by shi-yan** [alanlukezic/csr-dcf#16]
Hello there,

I have a question regarding the meaning of "channel". I thought it meant the RGB channel, but after looking at the video of channel reliability weights visualization, there are so many of them. I thought there should be only 3 weights, one for each color channel.

If there are so many of them, then, channel can't be the RGB channel. 

![Selection_002](https://user-images.githubusercontent.com/326807/57112583-807d6680-6cf5-11e9-9efd-424667a53e85.png)

But by reading the code, I still think channel here is really the RGB channel, right?

Then how come the visualization shows so many weights? 

Thanks,

**Comment by alanlukezic** [comment]
Even though input into the tracker is a RGB image, correlation filter is calculated on higher dimensional features. So, "channel" refers to a channel of multi-channel features: 18 channels of HoG + 1 channel of grayscale image + 10 channels of colornames feature image. Total feature channels is therefore 29, resulting in the same number of channel reliability weights.

**Comment by shi-yan** [comment]
Thank you for the answers! 

I installed Matlab and now am trying to debug to understand this code deeper.
