### ISSUE TITLE
about vot2017 results?

### ISSUE THREAD

**Issue by he010103** [alanlukezic/csr-dcf#4]
I run csr-dcf in vot2016 and its EAO is 0.3381, the same as claimed in paper. But the EAO in vot2017 is 0.2223, which is different from the EAO in the table of vot2017 results paper
[http://openaccess.thecvf.com/content_ICCV_2017_workshops/papers/w28/Kristan_The_Visual_Object_ICCV_2017_paper.pdf](url)

**Comment by alanlukezic** [comment]
Hi, thanks for pointing this out. The version that has been submitted to the VOT17 is a bit modified. 
The check for grayscale image does not contain the second part: || sum(abs(img0(:))) < 10 should be commented out in create_csr_tracker, line 46. This was helpful in some specific situations that occur in this challenge.

**Comment by he010103** [comment]
@alanlukezic Thanks for your answer. I commented the code and get the EAO of 0.2561 in VOT2017. Will the results be better if replacing the hog feature with vgg features?

**Comment by alanlukezic** [comment]
The tracking performance is typically boosted if more complex features (like VGG) are used, so I think that it should be similar here, but I haven't tested it yet...

**Comment by he010103** [comment]
@alanlukezic  Thanks!

**Comment by he010103** [comment]
@alanlukezic hi，recently I replace the hog and cn feature by vgg feature，but the EAO in VOT2017 decreased to 22.5. Should the parameter in the correlation filter be carefully modified? Is it necessary to normalize the cnn feature across the channel and the spatial? Thanks!

**Comment by alanlukezic** [comment]
I have not experimented with the VGG features in the CSR-DCF yet, so I cannot answer on this question. You should try different strategies (normalize/not normalize feature channels/turn off channels weights, etc.). An open question is also features from which layers should be used for tracking.

**Comment by he010103** [comment]
@alanlukezic  Thank you for the answer. I found that the feature of hog and cn is not strictly normalize. I use xi = (xi - min(x)) / (max(x) - min(x)) to normalize all the feature but the EAO drop to 23.83. I speculate that it may weaken the discrepancy of the feature of different channels. Do you try other way of normalization?
