### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by ahkarami** [alanlukezic/csr-dcf#6]
Dear @alanlukezic,
Thank you for your fantastic project. Does any Python version of this project exists? (or any plan for release python version)

**Comment by alanlukezic** [comment]
Hi, currently there is no Python version of this tracker available and we do not have a short-term plan to develop it. However, there is a C++ version of CSR-DCF which was recently included in OpenCV contrib tracking module.

**Comment by ahkarami** [comment]
Ok, Thank you.
